### ISSUE TITLE
if this node can compute the single value?

### ISSUE THREAD

**Issue by luoyuzju** [roboskel/rostune#2]
Hello gstavrinos, I have a question,if i can compute every node's CPU rate、RAM through the rostune。Because i run this launch but only see the total_infomation. Thanks!

**Comment by gstavrinos** [comment]
Hello @luoyuzju ! Apart from overall statistics, rostune produces information for all running nodes. When you run rostune along with your other nodes, you can use `rostopic list` to see all available topics. rostune provides a ros topic for each and every node running. 

Hope that helps. Hit me up with any more questions!

George

**Comment by gstavrinos** [comment]
I am closing this issue. Feel free to reopen it if you need further assistance.
